export default [
  {
    title: 'iPhones',
    content: [
      'iPhone SE (with NFC widget in control center)',
      'iPhone 7 (with NFC widget in control center)',
      'iPhone 8 (with NFC widget in control center)',
      'iPhone X (with NFC widget in control center)',
      'iPhone XR',
      'iPhone XS',
      'iPhone XS Max',
      'iPhone 11',
      'iPhone 11 Pro',
      'iPhone 11 Pro Max',
      'iPhone 12',
      'iPhone 12 Pro',
      'iPhone 12 Mini',
      'iPhone 12 Pro Max',
      'iPhone 13',
      'iPhone 13 Pro',
      'iPhone 13 Mini',
      'iPhone 13 Pro Max',
      'iPhone SE (2nd generation)',
      'all future iPhones',
    ],
  },
  {
    title: 'Pixels',
    content: [
      'Pixel',
      'Pixel XL',
      'Pixel 2',
      'Pixel 2XL',
      'Pixel 3',
      'Pixel 3XL',
      'Pixel 3A',
      'Pixel 3aXL',
      'Pixel 4',
      'all future Pixels',
    ],
  },
  {
    title: 'Galaxy',
    content: [
      'SIII',
      'S4',
      'S5',
      'S6',
      'S6 Edge',
      'S6 Edge+',
      'S7',
      'S7Edge',
      'S8',
      'S8+',
      'S9',
      'S9+',
      'S10',
      'S10 5G',
      'S10+',
      'S20',
      'S20+',
      'A20',
      'A20e',
      'A30',
      'A50',
      'A51',
      'Galaxy Fold',
      'Galaxy Fold 2',
      'all future Galaxies',
    ],
  },
  {
    title: 'Samsung',
    content: [
      'Note 8',
      'Note 9',
      'Note 10',
      'Note 10+',
      'Note 20',
      'Note 20 Ultra',
      'Note 20 Ultra Plus',
      'all future Samsungs',
    ],
  },
  {
    title: 'HTC',
    content: [
      'One M9',
      'Desire 10 Pro',
      'Exodus 1',
      'U11/Life/+',
      'Desire 12/12+',
      'U11 Eyes',
      'U12 Life',
      'U12+',
      'U19e',
      '19+',
      'all future HTC phones',
    ],
  },
  {
    title: 'Huawei',
    content: [
      'P10',
      'P10 Plus',
      'P10 Lite',
      'P20',
      'P20 Pro',
      'P20 Lite',
      'P30',
      'P30 Pro',
      'P30 Lite',
      'all future Huawei models',
    ],
  },
  {
    title: 'LG',
    content: [
      'G3',
      'Nexus 5X',
      'V10',
      'G4',
      'K10',
      'V20',
      'G5',
      'G6',
      'V30',
      'V35 ThinQ',
      'Q Stylus',
      'Q Stylo 4',
      'Stylo 5',
      'V40 ThinQ',
      'V50 ThinQ 5G',
      'Q8',
      'Q7',
      'G7 ThinQ',
      'G8',
      'G8s ThinQ',
      'Q9',
      'One',
      'all future LG phones',
    ],
  },
  {
    title: 'Xiaomi',
    content: [
      'Mi Mix',
      'Mi Mix2',
      'Mi Mix 2S',
      'Mi Mix 3',
      'Mi5',
      'Mi5s',
      'Mi5 Plus',
      'Mi6/X',
      'Mi6',
      'Mi8',
      'Mi8 Lite',
      'Mi8 Pro',
      'Mi9',
      'Mi9 SE',
      'all future Xiaomi phones',
    ],
  },
  {
    title: 'Nokia',
    content: [
      '3',
      '5',
      '6',
      '8',
      '8.1',
      '6.1',
      '8 Sirocco',
      '7 Plus',
      '5.1',
      '9 PureView',
      'all future Nokias',
    ],
  },
  {
    title: 'OnePlus',
    content: [
      'One',
      '3',
      '3T',
      '5',
      '5T',
      '6',
      '6T',
      '7',
      '7 Pro 5G',
      'all future OnePlus phones',
    ],
  },
  {
    title: 'Motorola',
    content: [
      'Moto P50',
      'Moto X4',
      'Moto Z3',
      'Moto Z3 Play',
      'all future Motorolas',
    ],
  },
  {
    title: 'Sony',
    content: [
      'Xperia XZ1/Compact',
      'Xperia 1',
      '10/Plus',
      'Xperia XA1/Ultra/Plus',
      'Xperia XZ2/Compact/Premium',
      'Xperia XA2/Ultra/Plus',
      'Xperia XZ3',
      'all future Sony phones',
    ],
  },
  {
    title: 'Essential',
    content: ['PH', 'PH-1', 'all future Essential phones'],
  },
];
