# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - sudo apt install curl 
      - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
      - source ~/.bashrc 
      - nvm ls
      - nvm install node 16.7.13
      - npm install -g yarn
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*